### ISSUE TITLE
only highlight full-line-comments, not inline comments

### ISSUE THREAD

**Issue by ZJoscha** [xavierog/codemirror-mode-pcre#1]
Hi thank you for the great work.

In my use-case i have list of regex, each regex starting on a new line. I want to allow comment-lines and the `(?#...)`-inline comment but dont want to highlight any inline occurrence of '#' till line-end as comment, except the line is a full-line comment (line starting with '#' with optional leading whitespaces).

Problem example:
![Problem-example](https://user-images.githubusercontent.com/16595918/179994779-d294edbd-b14e-4eb2-bb51-703b78dc0461.png)

Code that handles comments:  
https://github.com/xavierog/codemirror-mode-pcre/blob/0c7d3e45c07140a4e9791918bf8e1aff9b322122/src/pcre.js#L754-L758

My fix (pcre.js, Line 755):  
```javascript
// Regular comments in extended mode:
if (state.extended && stream.eat('#') && stream.string.match(/^\s*#/)) {
...
}
```

Behavior after fix:  
![Behavior-after-fix](https://user-images.githubusercontent.com/16595918/179995315-8cd6835f-0dee-4dc0-942f-57709f183ae5.png)

Is there a better way to implement my wished behavior?

**Comment by xavierog** [comment]
Hi,

> In my use-case [...]

I assume your use case implies to showcase single-line regexes along with full-line comments describing what they do? Is there something I am missing that makes end-of-line comments so problematic?

> Is there a better way to implement my wished behavior?

Possibly, yes:

- you could pass `extended: false` when creating the CodeMirror instance, thus disabling extended mode; this way, inline comments will still be highlighted as comments (they always are), but neither end-of-line comments nor full-line comments will be highlighted as comments.
- I could add an option (e.g.  `comments: true`) to highlight full-line comments even when extended mode is disabled.

That way, codemirror-mode-pcre could fulfil your use case out of the box.

**Comment by ZJoscha** [comment]
many thanks to you! - I learned something new today about the x-flag of pcre. pcre.js out-of-the-box behavior is totally correct. You can close this issue

**Comment by xavierog** [comment]
> many thanks to you! - I learned something new today about the x-flag of pcre.

That flag is admittedly a game-changer in the way one perceives, writes, maintains and reads regexes.

> pcre.js out-of-the-box behavior is totally correct.

Totally correct as far as PCRE is concerned (assuming enabling extended mode by default does not hurt).

> You can close this issue

Are you sure? Is your use case fully covered?

**Comment by ZJoscha** [comment]
> Are you sure? Is your use case fully covered?

well, some of my users are not firm with writing regex. To force them to write any whitespace in their lists of regexes as `\s` is just another burden to them. And it makes these lists more unreadable.

> I could add an option (e.g. comments: true) to highlight full-line comments even when extended mode is disabled.

So maybe this would help a little :)

**Comment by xavierog** [comment]
> To force them to write any whitespace in their lists of regexes as `\s` is just another burden to them.

They do not have to, be it in regular or extended mode. Specifically, extended mode simply ignores leading and trailing whitespaces so as to offer shell-like comments. If these whitespaces should be retained, it remains possible to use either `\s` or `\ `. Additionally, `\#` will be interpreted as "match a litteral # character" in both regular and extended modes.
In the end, PCRE syntax highlighting with extended mode enabled (the default) is a nice fit for lists of regexes... except if you frequently match "exactly one space followed by a # character" -- is that your use case? I would like to fully understand your situation before implementing extra options.

**Comment by ZJoscha** [comment]
Well ok here we go - my use case:  
We automatically read in many news from online feeds and webpages. All texts are stored in a postgres-database.
Now we have several departments that handle different topics: 
- Department A is interested in knowing all news to a specific topic f.e. "cars".
- Department B is only interested in news regarding f.e. "airports".

Users can create and edit a list of regexes, that are used to seek news that interests them / matching their department-specific domain.
Initially every line in the list was interpreted as single regex.
The regex-lists are used inside a postgresql-function to enable searching for matches on texts and extracting matches.
These matches are gathered and displayed to other users, that f.e. send out emails to the corresponding departments - "we got some news for you of topic XY".

As i mentioned earlier - some users are not firm on writing regex. So the input of valid regex should be as easy as can be. But others want to get really fancy with their regex - so complex syntax should be allowed as well.
The lists can get pretty long, so handling them is a pain (inside our quirky app). So users want to add empty-lines and comments, that must be preserved on save.
So my first try was changing the list-behavior, so that empty lines and full-line-comments are escaped on save and unescaped on load.
Other code and db-views make sure no escaped empty-line and comment-lines are used in the postgresql-function.

So when i first stumbled over pcre.js it seemed to match all my needs for syntax highlighting. But - due to the postgresql-function currently working without the x-flag - the syntax highlighting of pcre.js for inline-comments for `REGEX # comment` is   wrong, due the full string `"REGEX # comment"` is used as regex in postgresql-function.

Comments and empty lines work out-of-the-box when changing the postgresql-function to work with x-flag. But then all existing regexes must be reworked _(simply doable by db)_, due to the fact that the regex `\bracing car\b` is no longer matching on the string "Racing Car" but now on "RacingCar". More concerning is, that users have to keep in mind, not to write plain whitespace anymore - due to the x-flagged behavior.

***********************

By the way - initializing the CodeMirror instance with `extended: false` seems not to work at all in my usage - am i doing anything wrong? Inline comments `REGEX #comment` are still highlighted as comments:
```javascript
...
let editor = CodeMirror.fromTextArea($('#wordlist').get(0), {
		value: init_value,
		mode:  "pcre",
		extended: false,
		lineNumbers: true,
		autoRefresh: true,
		lineWrapping: true
	});
...
```

**Comment by ZJoscha** [comment]
> By the way - initializing the CodeMirror instance with extended: false seems not to work at all in my usage - am i doing anything wrong? Inline comments REGEX #comment are still highlighted as comments:

Found my mistake:
```javascript
let editor = CodeMirror.fromTextArea($('#wordlist').get(0), {
		value: init_value,
		mode: {name: "pcre", extended: false},
		lineNumbers: true,
		autoRefresh: true,
		lineWrapping: true
	});
```

**Comment by ZJoscha** [comment]
So it seems i want the best of both worlds
- writing regex without regarding x-flag
- extended syntax highlighting without eol-comments

I think my case is kinda quirky and not a common problem - i could life with my workaround mentioned above.

**Comment by ZJoscha** [comment]
little off-topic: 
When i want to use fancy extended mode for highlighting without x-flag matching in psql-function - do you know a way to extract "pure" regex literals (without any comments) out of pcre-regex containing comments?

**Comment by xavierog** [comment]
> Comments and empty lines work out-of-the-box when changing the postgresql-function to work with x-flag. But then all existing regexes must be reworked _(simply doable by db)_, due to the fact that the regex `\bracing car\b` is no longer matching on the string "Racing Car" but now on "RacingCar". More concerning is, that users have to keep in mind, not to write plain whitespace anymore - due to the x-flagged behavior.

Ok, I understand better. I am of course going to focus on the CodeMirror part. I see two main ways to reach your goal:

- the first way is to modify codemirror-mode-pcre and implement a "comments" option as described earlier;
- the second way is to acknowledge that a list of single-line regexes with support for empty lines and shell-like comments is not the same as an extended regex. Therefore, it should be possible to write a simple, dedicated CodeMirror mode that will do exactly what you want (including future improvements specific to your activity) while delegating all the regex part to pcre.js. Otherly put, instead of modifying codemirror-mode-pcre, one would write, say, codemirror-mode-regexlist, which would leverage codemirror-mode-pcre for most of the work. That way, we both end up with components that do their work and only their work.

**Comment by xavierog** [comment]
> little off-topic: When i want to use fancy extended mode for highlighting without x-flag matching in psql-function - do you know a way to extract "pure" regex literals (without any comments) out of pcre-regex containing comments?

The whole process is inherently error-prone but turning an extended PCRE into a non-extended one should be a matter of **removing** comments, non-escaped spaces and joining the remaining lines. That includes:
- removing full-line comments, i.e. stripping `^\s*#.*$`
- removing end-of-line comments, i.e. stripping `(?!\\)#.*$`
- optionally removing `(?#inline comments)`, i.e. stripping `\(\?#[^)]*\)`
- removing non-escaped spaces (i.e. all `(?!\\)\s`)
- stripping remaining \r and \n characters

This is clearly feasible but, again, definitely error-prone.

**Comment by ZJoscha** [comment]
> > little off-topic: When i want to use fancy extended mode for highlighting without x-flag matching in psql-function - do you know a way to extract "pure" regex literals (without any comments) out of pcre-regex containing comments?
> 
> The whole process is inherently error-prone but turning an extended PCRE into a non-extended one should be a matter of **removing** comments, non-escaped spaces and joining the remaining lines. That includes:
> 
> * removing full-line comments, i.e. stripping `^\s*#.*$`
> * removing end-of-line comments, i.e. stripping `(?!\\)#.*$`
> * optionally removing `(?#inline comments)`, i.e. stripping `\(\?#[^)]*\)`
> * removing non-escaped spaces (i.e. all `(?!\\)\s`)
> * stripping remaining \r and \n characters
> 
> This is clearly feasible but, again, definitely error-prone.

Yeah, that feels like going in the wrong direction by adding more fiddling.

> the first way is to modify codemirror-mode-pcre and implement a "comments" option as described earlier;

That would help in my case, but maybe in the end i am the only one using that feature xD.

> Therefore, it should be possible to write a simple, dedicated CodeMirror mode that will do exactly what you want (including future improvements specific to your activity) while delegating all the regex part to pcre.js.

That seems to be the best way, but seems to be a lot of work without any CodeMirror developing knowledge.
On front-page you wrote about nesting pcre.js . Would that be a way?
I will start by trying to understand the mentioned demo-page (my guess is thats the [index.html](https://github.com/xavierog/codemirror-mode-pcre/blob/0c7d3e45c07140a4e9791918bf8e1aff9b322122/index.html)) and [codemirror modeapi](https://codemirror.net/5/doc/manual.html#modeapi)

**Comment by xavierog** [comment]
Indeed, index.html provides a demonstration of a small CodeMirror mode for nginx (dubbed "mini-nginx"): this is the most relevant line, the one that delegates work to codemirror-mode-pcre:
https://github.com/xavierog/codemirror-mode-pcre/blob/0c7d3e45c07140a4e9791918bf8e1aff9b322122/index.html#L768

That option indeed implies to become familiar with CodeMIrror modes. But keep in mind that your format is currently quite simple, so you should not have to write a lot of code. Actually, you can probably reach your goal by simplifying mini-nginx.

**Comment by xavierog** [comment]
I am closing this issue. I assume you managed to turn mini-nginx into a mode for your custom format. Feel free to reopen if you still need help.

**Comment by ZJoscha** [comment]
hi, nah i cannot make it work.

i tried something like:
```javascript
CodeMirror.defineMode('wordlist-2-pcre', function(editor_options, mode_options) {
		let pcre_mode = CodeMirror.getMode(editor_options, {name: 'pcre', extended: false});
		return {
			startState: function() {
				return {
					current: '',
					pcre_state: CodeMirror.startState(pcre_mode),
					expect_regex: true, // whether the next string should be a regex
				};
			},
			copyState: function(os) { // os = original state
				return {
					current: os.current,
					pcre_state: CodeMirror.copyState(pcre_mode, os.pcre_state),
					expect_regex: os.expect_regex,
				};
			},
			token: function(stream, state) {
				console.log('stream', stream)
				console.log('state', state)
				
			        if (stream.eat(/[^#]/) && !stream.string.match(/^\s*#/)) {
				    state.current = 'regex';
				    state.pcre_state = CodeMirror.startState(pcre_mode);
				    return pcre_mode.token(stream, state.pcre_state)
			        }
					
				/* full line comment */
				if (stream.eat('#') && stream.string.match(/^\s*#/)) {
					stream.skipToEnd();
					return 'comment';
				}
				
				stream.next();
				return state.current;
			},
		};
	});
```
i cannot test this atm, but i got into a state, where regex-syntax highlighting kind of worked- but the highlighting was like offset one character - so like `\btext\b` was highlighted as **\b**tex**t\b**

will write again if i come to testing

**Comment by xavierog** [comment]
I'll have a look (no promises on "when" though).

**Comment by xavierog** [comment]
Try this:
```javascript
CodeMirror.defineMode('wordlist-2-pcre', function(editor_options, mode_options) {
    let pcre_mode = CodeMirror.getMode(editor_options, {name: 'pcre', extended: false});
    return {
        startState: function() {
            return { pcre_state: CodeMirror.startState(pcre_mode) };
        },
        copyState: function(os) { // os = original state
            return { pcre_state: CodeMirror.copyState(pcre_mode, os.pcre_state) };
        },
        token: function(stream, state) {
            if (stream.sol()) {
                if (stream.match(/^\s*#.*$/)) return 'comment';
                // New non-comment line, new PCRE state:
                state.pcre_state = CodeMirror.startState(pcre_mode);
            }
            return pcre_mode.token(stream, state.pcre_state);
        },
    };
});
```

**Comment by ZJoscha** [comment]
Working like a charm. Thanks alot!

**Comment by xavierog** [comment]
> Working like a charm.

Great!

>  Thanks alot!

You are welcome. Closing this issue now.
