### ISSUE TITLE
Broken bracket highlighting

### ISSUE THREAD

**Issue by Sicos1977** [xavierog/codemirror-mode-pcre#4]
Hi,

I came across your highlighter and it works great except for one thing. The matching bracket highlighting is broken.
It only works for { and } but not for other thing like ( and ) or [ and ]

Is there some kind of way to make this work again?

Here it works for the { and } ... see the box that is placed around it

![image](https://user-images.githubusercontent.com/6692947/230872138-86ca1681-c718-4417-b343-cb9c5667ece6.png)

But when I'm behind a  ) nothing happens.

![image](https://user-images.githubusercontent.com/6692947/230872278-aaab42e9-aa8a-44a7-92f8-881567ff20dd.png)

**Comment by xavierog** [comment]
Hi,

Thanks for your report.

> The matching bracket highlighting is broken.

I do not use it, which explains why I never noticed that before.

> Is there some kind of way to make this work again?

I guess so. I will look into it.

**Comment by Sicos1977** [comment]
I like the bracket highlighting because I sometimes get lost in all the groups that are in a regular expressions and with the bracket highlighting I better know what belongs together.

Thanks for looking into this.

**Comment by Sicos1977** [comment]
If I remove this part then the bracket highlighting works for the [ and ] but the grouping is then broken so it almost looks like you are somehow overriding the classes that are set to make the bracket highlighting work.

```javascript
if (current_state === 'character-class') {
	rem = stream.match(posix_named_sets_regex);
	if (rem) {
		if (rem[1] in posix_named_sets) return all_tokens(state, 'generic-character-type');
		else return all_tokens(state, 'err unknown-posix-class-name');
	}
	if (stream.eat(']')) return pop(state, 'character-class');
	consume(stream);
	return all_tokens(state);
}
```

**Comment by xavierog** [comment]
Let's start with diagnosing what happens exactly:
matchbracket's scanForBracket() function compares the current bracket's style with the matching bracket's style -- cf
https://github.com/codemirror/codemirror5/blob/9974ded36bf01746eb2a00926916fef834d3d0d0/addon/edit/matchbrackets.js#L71  -- and it expects them to be strictly equal. But this is not the case with codemirror-mode-pcre:
- {}: "cm-quantifier" vs "cm-quantifier" => strictly equal => works as expected
- []: "cm-character-class" vs "cm-character-class cm-character-class" => not strictly equal => does not work as expected
- (): "cm-group1 cm-start-group" vs " cm-group1 cm-end-group" => not equal at all (start vs end + leading space) => does not work at all

I am going to check how this could be handled properly. I guess I could:
- improve all_tokens() so it de-duplicates tokens and avoids that leading space
- replace `end-group` and `start-group` with `start-end-group`

**Comment by xavierog** [comment]
@Sicos1977 Could you please try out the patch below?

```diff
diff --git a/src/pcre.css b/src/pcre.css
index 528af0f..e22a675 100644
--- a/src/pcre.css
+++ b/src/pcre.css
@@ -8,7 +8,6 @@
 .cm-s-default span.cm-group8 { background: #aaffffa0; }
 
 .cm-s-default span.cm-start-group,
-.cm-s-default span.cm-end-group,
 .cm-s-default span.cm-alternation
 {
 	font-weight: bold;
diff --git a/src/pcre.js b/src/pcre.js
index de56cf9..2269c0a 100644
--- a/src/pcre.js
+++ b/src/pcre.js
@@ -401,7 +401,11 @@
 		}
 		function all_tokens(state, token) {
 			var result = state.context.join(' ');
-			if (token) result += ' ' + token;
+			if (token) {
+				// Avoid leading spaces as they confuse matchbrackets (see issue #4):
+				if (result) result += ' ';
+				result += token;
+			}
 			return result;
 		}
 		function push(state, new_context, new_context_state, token) {
@@ -759,7 +763,7 @@
 					if (rem[1] in posix_named_sets) return all_tokens(state, 'generic-character-type');
 					else return all_tokens(state, 'err unknown-posix-class-name');
 				}
-				if (stream.eat(']')) return pop(state, 'character-class');
+				if (stream.eat(']')) return pop(state);
 				consume(stream);
 				return all_tokens(state);
 			}
@@ -836,7 +840,7 @@
 
 			if (stream.peek() === ')') {
 				if (current_state && current_state.match(/^group/)) {
-					ret = 'end-group';
+					ret = 'start-group'; // formerly 'end-group' but that used to confuse matchbrackets (see issue #4)
 					if (current_context_state(state).leave_closing_parenthesis) ret = '';
 					else stream.next();
 					-- state.group_level;
```

**Comment by Sicos1977** [comment]
Sure I'll give it a try. Thanks for picking this up so quickly

**Comment by Sicos1977** [comment]
It's working now.

![image](https://user-images.githubusercontent.com/6692947/231058619-7bcfa5e7-0df5-415a-9ccf-52d3a2684def.png)

![image](https://user-images.githubusercontent.com/6692947/231058679-030d53cc-499f-4e03-9740-e08c766f43d5.png)

![image](https://user-images.githubusercontent.com/6692947/231058768-53acd49c-7d9a-461d-9246-586005c410a3.png)

**Comment by Sicos1977** [comment]
The only thing I now have to do is rebuild the highlighting a little bit because I'm using it to highlight C# regular expressions. They look a lot like php ones but there are some differences I still have to figure out. But your highlighter was the best I could find to highlight C# regular expressions. Almost none exists for other regular expression flavors in combination with codemirror.

I think that for some reason people don't see regular expressions as a "programming" language :-)

**Comment by xavierog** [comment]
> It's working now.

Ok, I will integrate the fix and release+publish a new version in the coming days.

>  C# regular expressions. They look a lot like php ones but there are some differences I still have to figure out.

Because it tried to mimic Perl, a language where regexes are first-class citizens, PCRE provides many features (and some pitfalls re: potential execution time), which C# / .NET have likely reused. Most likely, all C# features can be found in PCRE. If you want to be strict, you can remove parts of the syntax highlighting based on e.g. https://gist.github.com/CMCDragonkai/6c933f4a7d713ef712145c5eb94a1816 .

> I sometimes get lost in all the groups
> for some reason people don't see regular expressions as a "programming" language

By the way, have you considered using extended/verbose/free-spacing mode? https://www.regular-expressions.info/freespacing.html

**Comment by Sicos1977** [comment]
> > It's working now.
> 
> Ok, I will integrate the fix and release+publish a new version in the coming days.
> 
> > C# regular expressions. They look a lot like php ones but there are some differences I still have to figure out.
> 
> Because it tried to mimic Perl, a language where regexes are first-class citizens, PCRE provides many features (and some pitfalls re: potential execution time), which C# / .NET have likely reused. Most likely, all C# features can be found in PCRE. If you want to be strict, you can remove parts of the syntax highlighting based on e.g. https://gist.github.com/CMCDragonkai/6c933f4a7d713ef712145c5eb94a1816 .
> 
> > I sometimes get lost in all the groups
> > for some reason people don't see regular expressions as a "programming" language
> 
> By the way, have you considered using extended/verbose/free-spacing mode? https://www.regular-expressions.info/freespacing.html

I does not have to be dummy proof but before using your regex highlighter I even sometimes got lost in some regular expressions because they are so cryptic to read. And I'm fairly good in writing regex. But going from no highlighting at all to this is a major step forward.

Dark mode
![image](https://user-images.githubusercontent.com/6692947/231134027-56056d04-a2cc-460d-8b4e-8d62db73311b.png)

Light mode
![image](https://user-images.githubusercontent.com/6692947/231134166-59802037-d35e-4291-b8b1-555eae267b74.png)

**Comment by xavierog** [comment]
Ok, all done. I tagged a major version (2.0.0) because removing that `cm-end-group` CSS class potentially breaks existing custom themes (except yours since you likely wrote it based on [the patch](#issuecomment-1502048970)). I also published to [npm](https://www.npmjs.com/package/codemirror-mode-pcre/v/2.0.0).
This issue is now considered solved.
